# This is a GitHub Actions workflow template for running Linkspector on Markdown files.
# It is triggered on pull requests that modify Markdown files.
# The workflow checks for broken links in the Markdown files using the Linkspector action.
name: Check Markdown links
on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  markdown-link-check:
    name: Link-inspect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'

